
apiVersion: apps/v1
kind: Deployment
metadata:
  name: our-aks-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: springboot-app
        image: projectprodacr.azurecr.io/projectprodacr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aks-app
    k8s-app: aks-app
  name: aks-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085 
  type: LoadBalancer
  selector:
    app: aks-app
